import './globals.css'
import AppWalletProvider from './components/AppWalletProvider'
import { ReactQueryProvider } from './react-query-provider'
import Header from './components/Header'

export const metadata = {
  title: 'votee',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <AppWalletProvider>
            <Header />
            <main className="max-w-6xl mx-auto">{children}</main>
          </AppWalletProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
